name: Build Mod

on:
  push:
    branches: [ "26.2", "main", "master", "1.20.1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GIGA_CLIENT_ID: ${{ secrets.GIGA_CLIENT_ID }}
          GIGA_CLIENT_SECRET: ${{ secrets.GIGA_CLIENT_SECRET }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GigaChatMod-1.20.1
          path: build/libs/*.jar
